package cz.vaclavtolar.volebnizavod.util

import android.graphics.Color

enum class Party(val color: Int, val abbr: String? = null) {
    ANO(Color.parseColor("#261060"), "ANO"),
    ODS(Color.parseColor("#004494"), "ODS"),
    PIRATI(Color.parseColor("#000000"), "Piráti"),
    SPD(Color.parseColor("#2C86C4"), "SPD"),
    USVIT(Color.parseColor("#2C86C4"), "Úsvit"),
    KSCM(Color.parseColor("#D8261C"), "KSČM"),
    CSSD(Color.parseColor("#f29400"), "ČSSD"),
    KDU_CSL(Color.parseColor("#F9DA23"), "KDU-ČSL"),
    TOP09(Color.parseColor("#993399"), "TOP 09"),
    STAN(Color.parseColor("#b6c932"), "STAN"),
    SSO(Color.parseColor("#005F49"),),
    SZ(Color.parseColor("#009900"), "Zelení"),
    ROZUMNI(Color.parseColor("#cccccc"),),
    REALISTE(Color.parseColor("#cccccc"),),
    STRANA_PRAV_OBCANU(Color.parseColor("#996600"),),
    SPORTOVCI(Color.parseColor("#cccccc"),),
    DSSS(Color.parseColor("#cccccc"),),
    SPR_RSC(Color.parseColor("#cccccc"),),
    RN_VU(Color.parseColor("#cccccc"),),
    ODA(Color.parseColor("#cccccc"),),
    BPI_OD(Color.parseColor("#cccccc"),),
    REFERENDUM_EU(Color.parseColor("#cccccc"),),
    RC(Color.parseColor("#cccccc"),),
    COS(Color.parseColor("#cccccc"),),
    DV_2016(Color.parseColor("#cccccc"),),
    CSNS(Color.parseColor("#cccccc"),),
    CIBULKA(Color.parseColor("#cccccc"),),
    PROTI_DEVELOPERUM_PU(Color.parseColor("#cccccc"),),
    UNIE_HAVEL_2017(Color.parseColor("#cccccc"),),
    OBCANE_2011(Color.parseColor("#cccccc"),),
    NAROD_SOBE(Color.parseColor("#cccccc"),),
    CNF(Color.parseColor("#cccccc"),),
    HLAVA_VZHURU(Color.parseColor("#cccccc"),),
    ZMENA(Color.parseColor("#cccccc"),),
    STRANA_SOUKROMNIKU(Color.parseColor("#cccccc"),),
    SUVERENITA_STRANA_ROZUMU(Color.parseColor("#333333"),),
    AKTIV_NEZAVISLYCH_OBCANU(Color.parseColor("#cccccc"),),
    LEV21(Color.parseColor("#cccccc"),),
    KORUNA_CESKA(Color.parseColor("#cccccc"),),
    OBCANE_CZ(Color.parseColor("#cccccc"),),
    VECI_VEREJNE(Color.parseColor("#00D7FF"),),
    KONZERVATIVNI_STRANA(Color.parseColor("#cccccc"),),
    STOP(Color.parseColor("#cccccc"),),
    EVROPSKY_STRED(Color.parseColor("#cccccc"),),
    HUMINISTICKA_ALIANCE(Color.parseColor("#cccccc"),),
    KLICOVE_HNUTI(Color.parseColor("#cccccc"),),
    LIBERALOVE_CZ(Color.parseColor("#cccccc"),),
    NARODNI_PROSPERITA(Color.parseColor("#cccccc"),),
    MORAVANE(Color.parseColor("#cccccc"),),
    ROMSKA_DEMOKRATICKA_STRANA(Color.parseColor("#cccccc"),),
    KAN(Color.parseColor("#cccccc"),),
    STRANA_ZDRAVEHO_ROZUMU(Color.parseColor("#cccccc"),),
    CESKE_HNUTI_ZA_NARODNI_JEDNOTU(Color.parseColor("#cccccc"),),
    BALBINOVA_POETICKA_STRANA(Color.parseColor("#cccccc"),),
    LIBERARNI_REFORMNI_STRANA(Color.parseColor("#cccccc"),),
    PRAVO_A_SPRAVEDLNOST(Color.parseColor("#cccccc"),),
    NEZAVISLI(Color.parseColor("#cccccc"),),
    CESKA_PRAVICE(Color.parseColor("#cccccc"),),
    SNK_EVROPSTI_DEMOKRATE(Color.parseColor("#005ca1"),),
    UNIE_SVOBODY(Color.parseColor("#cccccc"),),
    HELAX_OSTRAVA_SE_BAVI(Color.parseColor("#cccccc"),),
    PRAVY_BLOK(Color.parseColor("#cccccc"),),
    _4_VIZE(Color.parseColor("#cccccc"),),
    HUMANISTICKA_STRANA(Color.parseColor("#cccccc"),),
    KOALICE_PRO_CR(Color.parseColor("#cccccc"),),
    NARODNI_STRANA(Color.parseColor("#cccccc"),),
    FOLKLOR_I_SPOLECNOST(Color.parseColor("#cccccc"),),
    NEZAVISLI_DEMOKRATE(Color.parseColor("#cccccc"),),
    STRANA_ROVNOST_SANCI(Color.parseColor("#cccccc"),),




}