package cz.vaclavtolar.volebnizavod.util

import cz.vaclavtolar.volebnizavod.util.Party.*

object PartyMappings {
    val SNEMOVNA_2017: Map<Int, Party> = mapOf(
        1 to ODS,
        2 to RN_VU,
        3 to COS,
        4 to CSSD,
        5 to CIBULKA,
        6 to RC,
        7 to STAN,
        8 to KSCM,
        9 to SZ,
        10 to ROZUMNI,
        11 to PROTI_DEVELOPERUM_PU,
        12 to SSO,
        13 to BPI_OD,
        14 to ODA,
        15 to PIRATI,
        16 to OBCANE_2011,
        17 to UNIE_HAVEL_2017,
        18 to CNF,
        19 to REFERENDUM_EU,
        20 to TOP09,
        21 to ANO,
        22 to DV_2016,
        23 to SPR_RSC,
        24 to KDU_CSL,
        25 to CSNS,
        26 to REALISTE,
        27 to SPORTOVCI,
        28 to DSSS,
        29 to SPD,
        30 to STRANA_PRAV_OBCANU,
        31 to NAROD_SOBE
    )
    val SNEMOVNA_2013: Map<Int, Party> = mapOf(
        1 to CSSD,
        2 to SSO,
        3 to PIRATI,
        4 to TOP09,
        5 to HLAVA_VZHURU,
        6 to ODS,
        7 to ROMSKA_DEMOKRATICKA_STRANA,
        8 to KAN,
        9 to ZMENA,
        10 to STRANA_SOUKROMNIKU,
        11 to KDU_CSL,
        12 to CIBULKA,
        13 to SUVERENITA_STRANA_ROZUMU,
        14 to AKTIV_NEZAVISLYCH_OBCANU,
        15 to STRANA_PRAV_OBCANU,
        16 to OBCANE_2011,
        17 to SPD,
        18 to DSSS,
        // 19
        20 to ANO,
        21 to KSCM,
        22 to LEV21,
        23 to SZ,
        24 to KORUNA_CESKA,
    )
    val SNEMOVNA_2010: Map<Int, Party> = mapOf(
        1 to OBCANE_CZ,
        2 to LIBERALOVE_CZ,
        // 3
        4 to VECI_VEREJNE,
        5 to KONZERVATIVNI_STRANA,
        6 to KSCM,
        7 to KORUNA_CESKA,
        8 to CSNS,
        9 to CSSD,
        10 to NARODNI_PROSPERITA,
        11 to SPR_RSC,
        12 to MORAVANE,
        13 to STRANA_PRAV_OBCANU,
        14 to STOP,
        15 to TOP09,
        16 to EVROPSKY_STRED,
        17 to KDU_CSL,
        18 to CIBULKA,
        19 to CSNS,
        20 to SZ,
        21 to SUVERENITA_STRANA_ROZUMU,
        22 to HUMINISTICKA_ALIANCE,
        23 to PIRATI,
        24 to DSSS,
        25 to SSO,
        26 to ODS,
        27 to KLICOVE_HNUTI
    )
    val SNEMOVNA_2006: Map<Int, Party> = mapOf(
        1 to STRANA_ZDRAVEHO_ROZUMU,
        2 to CESKE_HNUTI_ZA_NARODNI_JEDNOTU,
        3 to BALBINOVA_POETICKA_STRANA,
        4 to LIBERARNI_REFORMNI_STRANA,
        5 to PRAVO_A_SPRAVEDLNOST,
        6 to NEZAVISLI,
        7 to CESKA_PRAVICE,
        8 to KORUNA_CESKA,
        9 to ODS,
        10 to CSSD,
        11 to SNK_EVROPSTI_DEMOKRATE,
        12 to UNIE_SVOBODY,
        13 to HELAX_OSTRAVA_SE_BAVI,
        14 to PRAVY_BLOK,
        15 to _4_VIZE,
        16 to CSNS,
        17 to MORAVANE,
        18 to SZ,
        19 to HUMANISTICKA_STRANA,
        20 to KSCM,
        21 to KOALICE_PRO_CR,
        22 to NARODNI_STRANA,
        23 to FOLKLOR_I_SPOLECNOST,
        24 to KDU_CSL,
        25 to NEZAVISLI_DEMOKRATE,
        26 to STRANA_ROVNOST_SANCI,
    )

}